---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	calc_total_node(calc_total_node)
	convert_to_bdt_node(convert_to_bdt_node)
	convert_to_eur_node(convert_to_eur_node)
	convert_to_aus_node(convert_to_aus_node)
	__end__([<p>__end__</p>]):::last
	__start__ --> calc_total_node;
	calc_total_node -. &nbsp;AUS&nbsp; .-> convert_to_aus_node;
	calc_total_node -. &nbsp;BDT&nbsp; .-> convert_to_bdt_node;
	calc_total_node -. &nbsp;EUR&nbsp; .-> convert_to_eur_node;
	convert_to_aus_node --> __end__;
	convert_to_bdt_node --> __end__;
	convert_to_eur_node --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
