schema = [
    {'id': 'unit', 'label': 'Unit :', 'options': ['INNOWEB'], 'type': 'dropdown'},
    {'id': 'type', 'label': 'Type :', 'options': ['1', '2'], 'type': 'radio'},
    {'id': 'datetimeVar', 'label': 'Date :', 'type': 'datetime'},
    {'id': 'init_full_name__', 'label': 'Requisition Raised By :', 'type': 'text'},
    {'id': 'init_user_designation__', 'label': 'Designation :', 'type': 'text'},
    {'id': 'ProductType', 'label': 'Product Type :', 'options': ['1', '0'], 'type': 'radio'},
    {'id': 'payment_mode', 'label': 'Payment Mode', 'options': ['0', '1'], 'type': 'dropdown'},
    {'id': 'ProductConfiguration', 'label': 'Product Configuration :', 'type': 'text'},
    {'id': 'EstimatedAmount', 'label': 'Estimated Amount :', 'type': 'amount'},
    {'id': 'prepose', 'label': 'Purpose', 'type': 'text'},
    {'id': 'account_head', 'label': 'Account Head', 'type': 'text', 'required': True},
    {'id': 'account_head_code', 'label': 'Account Head Code', 'type': 'text', 'required': True},
    {'id': 'account_type', 'label': 'Account Type', 'type': 'text'},
    {'id': 'vendor_code', 'label': 'Vendor Code', 'options': [], 'type': 'dropdown', 'required': True},
    {'id': 'vendor_name', 'label': 'Vendor Name', 'options': [], 'type': 'dropdown', 'required': True},
    {'id': 'vendor_email', 'label': 'Vendor Email', 'type': 'text'},
    {
        'id': 'grid_opex_grid', 'label': '', 'type': 'grid',
        'fields': [
            {'id': 'grid-grid_opex_grid-text0000000005', 'label': 'Name of Item & Specification', 'type': 'textarea'},
            {'id': 'grid-grid_opex_grid-text0000000006', 'label': 'Existing Stock', 'type': 'number'},
            {'id': 'grid-grid_opex_grid-text0000000007', 'label': 'Earlier Purchase Rate(Tk.)', 'type': 'amount'},
            {'id': 'grid-grid_opex_grid-text0000000008', 'label': 'Quantity', 'type': 'number'},
            {'id': 'grid-grid_opex_grid-text0000000009', 'label': 'Recommended Unit Price( Tk)*', 'type': 'amount'},
            {'id': 'grid-grid_opex_grid-text0000000010', 'label': 'Total Price Taka', 'type': 'amount'}, ]

    },
    {'id': 'total_price', 'label': 'Grand Total Price Taka', 'type': 'amount'},
    {'id': 'in_word', 'label': 'In words', 'type': 'text'},
    {'id': 'q4a', 'label': 'Is this to meet a new demand or for a replacement ?', 'type': 'text'},
    {'id': 'q4b', 'label': 'Why it is needed for?', 'type': 'text'},
    {'id': 'q4c', 'label': 'How the organization will be benefited ?', 'type': 'text'},
    {'id': 'q4d', 'label': 'How the activities are running without this item ?', 'type': 'text'},
    {'id': 'q4e', 'label': 'What is the alternative of purchase ?', 'type': 'text'},
    {'id': 'q4f', 'label': 'Other justification\'s ?', 'type': 'textarea'},
    {'id': 'BudgetedStatus', 'label': 'Budgeted Status :', 'options': ['1', '0'], 'type': 'radio'},
    {'id': 'AmountIfBudgeted', 'label': 'If budget, Put the amount', 'type': 'amount'},
    {'id': 'HowWillFinance', 'label': '', 'type': 'text'},
    {'id': 'PurReqReceiveDate', 'label': 'Date of purchase requisition received', 'type': 'datetime'},
    {'id': 'qB1', 'label': 'Have competitive bids been obtained?', 'options': ['0', '1'], 'type': 'dropdown'},
    {'id': 'qB2', 'label': 'How many quotation received?', 'type': 'number'},
    {'id': 'qB3', 'label': 'Comparative statement attached ?', 'options': ['0', '1'], 'type': 'dropdown'},
    {'id': 'qB4', 'label': 'Name of selected Supplier/Vendor?', 'type': 'text'},
    {'id': 'qbjustification1', 'label': '', 'type': 'text'},
    {'id': 'qbjustification2', 'label': '', 'type': 'text'},
    {'id': 'qbjustification3', 'label': '', 'type': 'text'},
    {'id': 'qbjustification4', 'label': '', 'type': 'text'},
    {'id': 'qbjustification5', 'label': '', 'type': 'text'},
    {'id': 'qB5', 'label': 'Recommended amount:', 'type': 'amount'},
    {'id': 'qB6', 'label': 'Payment mode', 'options': ['0', '1'], 'type': 'dropdown'},
    {'id': 'qB8', 'label': 'Retention of payment, if any:', 'type': 'text'},
    {'id': 'po_date', 'label': 'PO Date', 'type': 'datetime'},
    {'id': 'po_quantity', 'label': 'PO Quantity', 'type': 'number'},
    {'id': 'po_amount', 'label': 'PO Amount (With Vat & Tax)', 'type': 'amount'},
    {'id': 'po_vat_amount', 'label': 'VAT Amount', 'type': 'amount'},
    {'id': 'po_tax_amount', 'label': 'TAX Amount', 'type': 'amount'},
    {'id': 'advance_required', 'label': 'Advance Required', 'options': ['Yes', 'No'], 'type': 'radio'},
    {'id': 'advance_amount', 'label': 'Advance Amount', 'type': 'amount'},
    {'id': 'terms_condition', 'label': 'Terms & Condition', 'type': 'textarea'},
    {
        'id': 'grid_payment_term', 'label': 'Payment Term', 'type': 'grid',
        'fields': [
            {'id': 'grid-grid_payment_term-payment_term', 'label': 'Payment Term', 'type': 'text'},
            {'id': 'grid-grid_payment_term-amount', 'label': 'Amount', 'type': 'amount'}
        ]
    },
    {'id': 'file0000000001', 'label': 'Initiator Attachment', 'type': 'file'},
    {'id': 'file0000000002', 'label': 'IT/Admin Attachment', 'type': 'file'},
    {'id': 'file0000000003', 'label': 'Finance Attachment', 'type': 'file'},
    {'id': 'file0000000004', 'label': 'Attachment', 'type': 'file'},
    {'id': 'comment', 'label': 'Comment', 'type': 'textarea'},
    {'id': 'po_number', 'label': 'PO Number', 'type': 'text'},
    {'id': 'attention', 'label': 'Attention', 'type': 'text'},
    {'id': 'subject', 'label': 'Subject', 'type': 'text'},
    {'id': 'to_address', 'label': 'To Address', 'type': 'textarea'},
    {'id': 'delivery_address', 'label': 'Delivery Addres', 'type': 'textarea'},
    {'id': 'description', 'label': 'Description', 'type': 'textarea'},
    {'id': 'good_receive_note', 'label': 'Received Quantity', 'type': 'number'},
    {'id': 'challan_no', 'label': 'Challan Number', 'type': 'text'},
    {'id': 'receive_date', 'label': 'Receive Date', 'type': 'datetime'},
    {'id': 'total_receive', 'label': 'Total Receive (%)',
     'options': ['0%', '20%', '21%', '22%', '23%', '24%', '25%', '26%', '27%', '28%', '29%', '30%', '31%',
                 '32%', '33%', '34%', '35%', '36%', '37%', '38%', '39%', '40%', '41%', '42%', '43%', '44%',
                 '45%', '46%', '47%', '48%', '49%', '50%', '51%', '52%', '53%', '54%', '55%', '56%', '57%',
                 '58%', '59%', '60%', '61%', '62%', '63%', '64%', '65%', '66%', '67%', '68%', '69%', '70%',
                 '71%', '72%', '73%', '74%', '75%', '78%', '79%', '80%', '81%', '82%', '83%', '84%', '85%',
                 '86%', '87%', '88%', '89%', '90%', '91%', '92%', '93%', '94%', '95%', '96%', '97%', '98%',
                 '99%', '100%'], 'type': 'dropdown'},
    {'id': 'receive_status', 'label': 'Receive Status', 'options': ['Partial', 'Complete'], 'type': 'radio'},
    {'id': 'grn_remarks', 'label': 'Remarks', 'type': 'textarea'},
    {'id': 'file0000000005', 'label': 'GRN Doc', 'type': 'file'},
    {'id': 'grid-grid_opex_grid-text0000000011', 'label': 'Name of Vendor*', 'type': 'textarea'},
    {'id': 'qB7', 'label': 'Payment term', 'type': 'text'},
    {'id': 'RequisitionRaisedBy', 'label': 'Requisition Raised By :', 'type': 'text'},
    {'id': 'Designation', 'label': 'Designation :', 'type': 'text'},
    {'id': 'Status', 'label': 'Status', 'options': ['1', '2', '0'], 'type': 'dropdown'},
    {'id': 'checked', 'label': 'COA Checked', 'options': ['1', '0'], 'type': 'checkbox'},
    {'id': 'invoice_number', 'label': 'Invoice Number', 'type': 'text'},
    {'id': 'invoice_date', 'label': 'Invoice Date', 'type': 'datetime'},
    {'id': 'invoice_amount', 'label': 'Invoice Amount (With VAT & Tax)', 'type': 'amount'},
    {'id': 'file0000000006', 'label': 'Invoice Attachment', 'type': 'file'},
    {'id': 'total_payable_portion', 'label': 'Total Payable (%)', 'type': 'text'},
    {'id': 'payable_amount_vat_tax', 'label': 'Payable (With VAT & Tax)', 'type': 'amount'},
    {'id': 'invoice_vat', 'label': 'VAT', 'type': 'amount'},
    {'id': 'invoice_tax', 'label': 'TAX', 'type': 'amount'},
    {'id': 'payable_amount', 'label': 'Payable (without VAT & Tax)', 'type': 'amount'},
    {'id': 'payment_status', 'label': 'Payment Status', 'options': ['Partial', 'Complete'], 'type': 'radio'},
    {'id': 'total_send_amount_fin', 'label': 'Total send amount to fin', 'type': 'amount'}
]
